services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: talyn_app
    container_name: talyn_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - talyn

  db:
    image: mariadb:latest
    container_name: talyn_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - talyn

  redis:
    image: redis:latest
    container_name: talyn_redis
    restart: unless-stopped
    networks:
      - talyn

  nginx:
    image: nginx:alpine
    container_name: talyn_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - talyn
    depends_on:
      - app

networks:
  talyn:
    driver: bridge

volumes:
  dbdata:
    driver: local
